/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.concurrent.atomic.AtomicInteger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(final String[] args) {
        final InputStream fileInputStream = App.class.getResourceAsStream("/input.txt");
        final BufferedReader reader = new BufferedReader(new InputStreamReader(fileInputStream));
        final int[] dialPosition = {50};
        final AtomicInteger counter = new AtomicInteger(0);
        reader.lines().forEach(line -> {
            final String direction = line.substring(0, 1);
            final int distance = Integer.parseInt(line.substring(1));
            final boolean beforePos = dialPosition[0] > 0;
            if(direction.equals("R")) {
                dialPosition[0] += distance;
            } else {
                dialPosition[0] -= distance;
            }
            if(dialPosition[0] <= 0 && beforePos) counter.incrementAndGet();
            counter.addAndGet(Math.abs(dialPosition[0]) / 100);
            dialPosition[0] = dialPosition[0] % 100;
            if (dialPosition[0] < 0) dialPosition[0] += 100;
        });
        System.out.println(counter.get());
    }
}
