/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.concurrent.atomic.AtomicInteger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(final String[] args) {
        InputStream fileInputStream = App.class.getResourceAsStream("/input.txt");
        BufferedReader reader = new BufferedReader(new InputStreamReader(fileInputStream));
        int[] dialPosition = {50};
        AtomicInteger counter = new AtomicInteger(0);
        reader.lines().forEach(line -> {
            String direction = line.substring(0, 1);
            int distance = Integer.parseInt(line.substring(1));
            if(direction.equals("R")) {
                dialPosition[0] += distance;
                dialPosition[0] = dialPosition[0] % 100;
                if(dialPosition[0] == 0) {
                    counter.incrementAndGet();
                }
            } else {
                dialPosition[0] -= distance;
                dialPosition[0] = dialPosition[0] % 100;
                if(dialPosition[0] == 0) {
                    counter.incrementAndGet();
                }
            }
        });
        System.out.println(counter.get());
    }
}
